#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

FILES_DIR="$SCRIPT_DIR/files"

if ! type ansible-playbook >/dev/null; then
  if [ "$USE_HOMEBREW" = 'true' ]; then
    brew install ansible
  else
    # ref: https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html
    case "$OS_ID" in
      Debian )
        sudo cp "$FILES_DIR/usr/share/keyrings/ansible-ppa-keyring.gpg" /usr/share/keyrings/ansible-ppa-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ansible-ppa-keyring.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu $COMPATIBLE_UBUNTU_CODENAME main" \
          | sudo tee /etc/apt/sources.list.d/ansible.list
        sudo apt update && sudo apt install -y ansible
        ;;
      Ubuntu )
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
        ;;
      *)
        echo "Unsupported OS: $OS_ID" >&2
        exit 1
        ;;
    esac
  fi
fi
