#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TASKS_DIR="$SCRIPT_DIR/tasks"
UTILS_DIR="$SCRIPT_DIR/utils"
PLAYBOOK_DIR="$SCRIPT_DIR/ansible-playbook"

source "$UTILS_DIR/detect_os.bash"
detect_os

echo "---- Setup base ----"
"$TASKS_DIR/base/install"

echo "---- Install homebrew ----"
"$TASKS_DIR/homebrew/install"

source "$TASKS_DIR/homebrew/shellenv.bash"
shellenv

echo "---- Install Ansible ----"
"$TASKS_DIR/ansible/install"

echo "---- Play Ansible ----"
ansible-galaxy collection install -r "$PLAYBOOK_DIR/collections/requirements.yml"
ansible-playbook \
  --verbose \
  --diff \
  --ask-become-pass \
  --inventory "$PLAYBOOK_DIR/inventories/local.yml" \
  "$PLAYBOOK_DIR/playbook.yml"
