---
- name: Install xquartz by Homebrew
  community.general.homebrew_cask:
    name:
      - xquartz
    state: present
  when: install_xquartz

- name: Install extra apps by Homebrew
  community.general.homebrew_cask:
    name:
      - ipe
    state: present
  when: install_ipe

- name: Install extra apps by Homebrew
  community.general.homebrew_cask:
    name:
      - zotero
    state: present
  when: install_zotero
