---
- name: Directory of ssh config is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh/conf.d'
    state: directory
    recurse: true

- name: Directory of ssh private keys is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh/ppkey'
    state: directory
    mode: '0700'

- name: Copy ssh config
  ansible.builtin.copy:
    src: home/user/.ssh/config
    dest: '{{ ansible_env.HOME }}/.ssh/config'

- name: Copy ssh hosts config
  ansible.builtin.template:
    src: home/user/.ssh/conf.d/hosts.conf.j2
    dest: '{{ ansible_env.HOME }}/.ssh/conf.d/hosts.conf'
