tap "neovim/neovim"
tap "sanemat/font"
tap "adoptopenjdk/openjdk"

# common
brew "fish"
brew "arp-scan"
brew "python"
brew "gcc"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "nkf"
brew "nmap"
brew "neovim"
brew "wget"
brew "tmux"

# useful tools
brew "anyenv"
brew "direnv"
brew "gettext"
brew "jq"
brew "go"
brew "w3m"
brew "sbt"
brew "poppler"

# advanced tools
brew "bats"

# more advanced
#tap "lampepfl/brew"
#brew "llvm@6"
#brew "idris"
#brew "elm"
#brew "scala"
#brew "opam"
#brew "purescript"
#brew "lampepfl/brew/dotty"
#brew "subversion"
