#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$SCRIPT_DIR/shellenv.bash"
shellenv

if ! type brew >/dev/null; then
  # ref: https://brew.sh/index
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

case "$OS_ID" in
  Debian )
    if ! type gcc >/dev/null; then
      sudo apt-get install -y build-essential
    fi
    ;;
  *)
    # nothing
    ;;
esac
