---
install_xquartz: true
install_ipe: true
install_zotero: true
install_tex: true

git_user:
  name: Mizunashi Mana
  email: contact@mizunashi.work

ssh_conf_hosts:
  gitlab.com:
    host_name: gitlab.com
    user: git

  github.com:
    host_name: github.com
    user: git
