#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
FILES_DIR="$SCRIPT_DIR/files"

source "$SCRIPT_DIR/../../utils/all.bash"


if ! type git >/dev/null; then
  brew install git
fi

if ! type git-lfs >/dev/null; then
  brew install git-lfs
  git lfs install
fi


mkdir -p "$HOME/.config/git"

copy_with_backup "$FILES_DIR/config" "$HOME/.config/git/config"
copy_with_backup "$FILES_DIR/global.gitignore" "$HOME/.config/git/global.gitignore"

if ! [ -e "$HOME/.config/git/config.local" ]; then
  copy_with_backup "$FILES_DIR/config.local" "$HOME/.config/git/config.local"
fi
