---
- name: Directory of dircolors is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/dircolors'
    state: directory
    mode: '0755'

- name: Copy dircolors config
  ansible.builtin.copy:
    src: home/user/.config/dircolors/dark-256
    dest: '{{ ansible_env.HOME }}/.config/dircolors/dark-256'
