---
- name: Directory of local bin is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.local/bin'
    state: directory
    mode: '0755'

- name: uni-str-check is available
  ansible.builtin.copy:
    src: home/user/.local/bin/uni-str-check
    dest: '{{ ansible_env.HOME }}/.local/bin/uni-str-check'
    mode: '0755'
    validate: 'python3 %s test'

- name: record-io is available
  ansible.builtin.copy:
    src: home/user/.local/bin/record-io
    dest: '{{ ansible_env.HOME }}/.local/bin/record-io'
    mode: '0755'
