---
- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: present

- name: Install AstroNvim
  ansible.builtin.git:
    repo: 'https://github.com/AstroNvim/AstroNvim'
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    version: v3.42.0
