---
- name: Install by Homebrew
  include_tasks: install_by_homebrew.yml
  when: ansible_env.USE_HOMEBREW == 'true'

- name: Install AstroNvim
  ansible.builtin.git:
    repo: 'https://github.com/AstroNvim/AstroNvim'
    dest: '{{ ansible_env.HOME }}/.config/nvim'
    version: v3.42.0
