# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "chokidar-5.0.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-5.0.0.tgz";
        sha512 = "TQMmc3w+5AxjpL8iIiwebF73dRDF4fBIieAqGn9RGCWaEVwQ6Fb2cGe31Yns0RRIzii5goJ1Y7xbMwo1TxMplw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "playwright-1.59.0-alpha-1771104257000" = {
      name = "playwright";
      packageName = "playwright";
      version = "1.59.0-alpha-1771104257000";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright/-/playwright-1.59.0-alpha-1771104257000.tgz";
        sha512 = "6SCMMMJaDRsSqiKVLmb2nhtLES7iTYawTWWrQK6UdIGNzXi8lka4sLKRec3L4DnTWwddAvCuRn8035dhNiHzbg==";
      };
    };
    "playwright-core-1.59.0-alpha-1771104257000" = {
      name = "playwright-core";
      packageName = "playwright-core";
      version = "1.59.0-alpha-1771104257000";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright-core/-/playwright-core-1.59.0-alpha-1771104257000.tgz";
        sha512 = "YiXup3pnpQUCBMSIW5zx8CErwRx4K6O5Kojkw2BzJui8MazoMUDU6E3xGsb1kzFviEAE09LFQ+y1a0RhIJQ5SA==";
      };
    };
    "readdirp-5.0.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-5.0.0.tgz";
        sha512 = "9u/XQ1pvrQtYyMpZe7DXKv2p5CNvyVwzUB6uhLAnQwHMSgKMBR62lc7AHljaeteeHXn11XTAaLLUVZYVZyuRBQ==";
      };
    };
    "zod-4.3.6" = {
      name = "zod";
      packageName = "zod";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-4.3.6.tgz";
        sha512 = "rftlrkhHZOcjDwkGlnUtZZkvaPHCsDATp4pGpuOOMDaTdDDXF91wuVDJoWoPsKX/3YPQ5fHuF3STjcYyKr+Qhg==";
      };
    };
  };
in
{
  "@anthropic-ai/claude-code-" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "2.1.50";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-2.1.50.tgz";
      sha512 = "urrhY4IRuLHFoEYb6pjRy6sbDE8TH886zwRvIAPS4Tz51MeGVomZet4EajqxX6+IOKbJNbf4IHL3fTzI0vcKXA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@mizunashi_mana/cc-voice-reporter-" = nodeEnv.buildNodePackage {
    name = "_at_mizunashi_mana_slash_cc-voice-reporter";
    packageName = "@mizunashi_mana/cc-voice-reporter";
    version = "2.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@mizunashi_mana/cc-voice-reporter/-/cc-voice-reporter-2.0.0.tgz";
      sha512 = "xKz2n85t+iN0EFuhw2fFqKZNV/Ww8Vic4wBDk/XX7gfHjb6RAblYi3Lgt9fbIyq9HYIvvSJeidtVaYI2Nro8jA==";
    };
    dependencies = [
      sources."chokidar-5.0.0"
      sources."readdirp-5.0.0"
      sources."zod-4.3.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Real-time voice reporting for Claude Code";
      homepage = "https://github.com/mizunashi-mana/cc-voice-reporter";
      license = "Apache-2.0 OR MPL-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@openai/codex-" = nodeEnv.buildNodePackage {
    name = "_at_openai_slash_codex";
    packageName = "@openai/codex";
    version = "0.104.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@openai/codex/-/codex-0.104.0.tgz";
      sha512 = "pPa2VGHozwjPsPOYAEXcH7nNt1QH7AZR8zV8jYx6BFi1LJlmJkan2rvIS4MYbPdi2O6cd5kWfPCAHE0fEV2ifA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p align=\"center\"><code>npm i -g @openai/codex</code><br />or <code>brew install --cask codex</code></p> <p align=\"center\"><strong>Codex CLI</strong> is a coding agent from OpenAI that runs locally on your computer. <p align=\"center\">   <img src=\"https://";
      homepage = "https://github.com/openai/codex#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@playwright/cli-" = nodeEnv.buildNodePackage {
    name = "_at_playwright_slash_cli";
    packageName = "@playwright/cli";
    version = "0.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@playwright/cli/-/cli-0.1.1.tgz";
      sha512 = "9k11ZfDwAfMVDDIuEVW1Wvs8SoDNXIY1dNQ+9C9/SS8ZmElkcxesu5eoL7vNa96ntibUGaq1TM2qQoqvdl/I9g==";
    };
    dependencies = [
      sources."minimist-1.2.8"
      sources."playwright-1.59.0-alpha-1771104257000"
      sources."playwright-core-1.59.0-alpha-1771104257000"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Playwright CLI";
      homepage = "https://playwright.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
