#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
FILES_DIR="$SCRIPT_DIR/files"

source "$SCRIPT_DIR/../../utils/all.bash"


if ! type fish >/dev/null 2>&1; then
  brew install fish
fi


mkdir -p "$HOME/.config/fish"
mkdir -p "$HOME/.config/fish/functions"

copy_with_backup "$FILES_DIR/config.fish" "$HOME/.config/fish/config.fish"
for FISH_FUNCTION_FILE in "$FILES_DIR/functions"/*; do
  copy_with_backup "$FISH_FUNCTION_FILE" "$HOME/.config/fish/functions/$(basename "$FISH_FUNCTION_FILE")"
done

if ! grep "$(which fish)" /etc/shells; then
  sudo echo "$(which fish)" >> /etc/shells
fi
if ! (finger "$USER" | grep "Shell: $(which fish)"); then
  chsh -s "$(which fish)"
fi
