---
- name: Install git
  community.general.homebrew:
    name:
      - git
      - git-lfs
    state: present

- name: Directory of git config is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/git'
    state: directory
    recurse: true

- name: Copy git config
  ansible.builtin.copy:
    src: home/user/.config/git/config
    dest: '{{ ansible_env.HOME }}/.config/git/config'

- name: Copy global gitignore
  ansible.builtin.copy:
    src: home/user/.config/git/global.gitignore
    dest: '{{ ansible_env.HOME }}/.config/git/global.gitignore'

- name: Copy user config
  ansible.builtin.template:
    src: home/user/.config/git/user.config.j2
    dest: '{{ ansible_env.HOME }}/.config/git/user.config'
