---
- name: Check install by Homebrew
  set_fact:
    git_install_by: install_by_homebrew.yml
  when: ansible_env.USE_HOMEBREW == 'true' and ansible_env.OS_ID == 'macOS'

- name: Check install by apt
  set_fact:
    git_install_by: install_by_apt.yml
  when: |
    git_install_by is not defined
    and (
      ansible_env.OS_ID == 'Debian'
      or ansible_env.OS_ID == 'Ubuntu'
    )

- name: Install
  include_tasks: '{{ git_install_by }}'
  when: git_install_by is defined

- name: Directory of git config is available
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/git'
    state: directory
    recurse: true

- name: Copy git config
  ansible.builtin.copy:
    src: home/user/.config/git/config
    dest: '{{ ansible_env.HOME }}/.config/git/config'

- name: Copy global gitignore
  ansible.builtin.copy:
    src: home/user/.config/git/global.gitignore
    dest: '{{ ansible_env.HOME }}/.config/git/global.gitignore'

- name: Copy user config
  ansible.builtin.template:
    src: home/user/.config/git/user.config.j2
    dest: '{{ ansible_env.HOME }}/.config/git/user.config'
