---
- name: Install useful softwares
  hosts: all

  roles:
    - ssh_conf
    - dircolors
    - git
    - fish
    - neovim
    - vagrant
    - docker
    - direnv
    - devtools
    - extra_apps

  tasks:
    - ansible.builtin.include_role:
        name: tex
      when: install_tex
