---
- name: Check install by Homebrew
  set_fact:
    base_install_by: install_by_homebrew.yml
  when: ansible_env.USE_HOMEBREW == 'true'

- name: Check install by apt
  set_fact:
    base_install_by: install_by_apt.yml
  when: |
    base_install_by is not defined
    and (
      ansible_env.OS_ID == 'Debian'
      or ansible_env.OS_ID == 'Ubuntu'
    )

- name: Install
  include_tasks: '{{ base_install_by }}'
  when: base_install_by is defined
