---
- name: Copy gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/docker-archive-keyring.gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: Install docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  become: true
  when: ansible_env.OS_ID == 'Ubuntu'

- name: Install docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present
  become: true
  when: ansible_env.OS_ID == 'Debian'

- name: Install docker
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
  become: true
