---
- name: Copy hashicorp gpg key
  ansible.builtin.copy:
    src: usr/share/keyrings/hashicorp-archive-keyring.gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Install hashicorp repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
    state: present

- name: Install vagrant
  ansible.builtin.apt:
    name: vagrant
    state: present
  become: true
