---
- name: Install by Homebrew
  include_tasks: install_by_homebrew.yml
  when: ansible_env.OS_ID == 'macOS'

- name: Install by Debian
  include_tasks: install_by_apt.yml
  when: ansible_env.OS_ID == 'Debian'
