#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = "true" ] && set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
FILES_DIR="$SCRIPT_DIR/files"


if ! [ -d "$HOME/.local/share/dein" ]; then
  sh -c "$(curl -fsSL 'https://raw.githubusercontent.com/Shougo/dein-installer.vim/master/installer.sh')"
fi

nvim -V2 -es -c ':q'
